#pragma once
#include <string>
#include <vector>
#include <unordered_map>

class LegendaryLords {
public:
	std::vector<std::string> LordList = {
		"Thorgrim Grudgebearer",
		"Ungrim Ironfist",
		"Grombrindal",
		"Belegar Ironhammer",
		"Emperor Karl Franz",
		"Balthasar Gelt",
		"Volkmar the Grim",
		"Markus Wulfhart",
		"Manfred von Carstein",
		"Helman Ghorst",
		"Vlad von Carstein",
		"Isabella von Carstein",
		"Heinrich Kemmler",
		"Grimgor Ironhide",
		"Azhag the Slaughter",
		"Wurrzag",
		"Skarsnik",
		"Khazrak the One-Eye",
		"Malagor the Dark Omen",
		"Morghur the Shadowgrave",
		"Archaon the Everchosen",
		"Sigvald the Magnificent",
		"Kholek Suneater",
		"King Louen Leoncoeur",
		"Alberic de Bordelaux",
		"The Fay Enchantress",
		"Orion",
		"Durthu",
		"Wulfrik the Wanderer",
		"Throgg",
		"Tyrion",
		"Teclis",
		"Alith Anar",
		"Alarielle the Radiant",
		"Malekith",
		"Morathi",
		"Lokhir Fellheart",
		"Crone Hellebron",
		"Lord Mazdamundi",
		"Krow-Gar",
		"Tiktaq'to",
		"Tehenauin",
		"Gor-Rok",
		"Nakai the Wanderer",
		"Queek Headtaker",
		"Lord Skrolk",
		"Tretch Craventail",
		"Ikit Claw",
		"Settra the Imperishable",
		"High Queen Khalida",
		"Grand Hierophant Khatep",
		"Arkhan the Black",
		"Luthor Harkon",
		"Count Noctilus",
		"Aranessa Saltspite",
		"Cylostra Direfin"
	};

	std::vector<std::string> Races = {
		"Dwarfs",
		"The Empire",
		"Vampire Counts",
		"Greenskins",
		"Beastmen",
		"Warriors of Chaos",
		"Bretonnia",
		"Wood Elves",
		"Norsca",
		"High Elves",
		"Dark Elves",
		"Lizardmen",
		"Skaven",
		"Tomb Kings",
		"Vampire Coast"
	};

	std::unordered_map<std::string, std::vector<std::string>> TotalFactions = {
		{"Dwarfs",
		{"Thorgrim Grudgebearer",
		"Ungrim Ironfist",
		"Grombrindal",
		"Belegar Ironhammer"}},
		{"The Empire", {"Emperor Karl Franz",
		"Balthasar Gelt",
		"Volkmar the Grim",
		"Markus Wulfhart"}},
		{"Vampire Counts", {"Manfred von Carstein",
		"Helman Ghorst",
		"Vlad von Carstein",
		"Isabella von Carstein",
		"Heinrich Kemmler"}},
		{"Greenskins", {"Grimgor Ironhide",
		"Azhag the Slaughter",
		"Wurrzag",
		"Skarsnik"}},
		{"Beastmen", {"Khazrak the One-Eye",
		"Malagor the Dark Omen",
		"Morghur the Shadowgrave"}},
		{"Warriors of Chaos", {"Archaon the Everchosen",
		"Sigvald the Magnificent",
		"Kholek Suneater"}},
		{"Bretonnia", {"King Louen Leoncoeur",
		"Alberic de Bordelaux",
		"The Fay Enchantress"}},
		{"Wood Elves", {"Orion", "Durthu"}},
		{"Norsca", {"Wulfrik the Wanderer", "Throgg"}},
		{"High Elves", {"Tyrion",
		"Teclis",
		"Alith Anar",
		"Alarielle the Radiant"}},
		{"Dark Elves", {"Malekith",
		"Morathi",
		"Lokhir Fellheart",
		"Crone Hellebron"}},
		{"Lizardmen", {"Lord Mazdamundi",
		"Krow-Gar",
		"Tiktaq'to",
		"Tehenauin",
		"Gor-Rok",
		"Nakai the Wanderer"}},
		{"Skaven", {"Queek Headtaker",
		"Lord Skrolk",
		"Tretch Craventail",
		"Ikit Claw"}},
		{"Tomb Kings", {"Settra the Imperishable",
		"High Queen Khalida",
		"Grand Hierophant Khatep",
		"Arkhan the Black"}},
		{"Vampire Coast", {"Luthor Harkon",
		"Count Noctilus",
		"Aranessa Saltspite",
		"Cylostra Direfin"}}
	};
};