#pragma once
#include <string>
#include <vector>
#include <unordered_map>

class LegendaryLords {
public:
	std::vector<std::string> LordList = {
		"Thorgrim Grudgebearer",
		"Ungrim Ironfist",
		"Grombrindal",
		"Belegar Ironhammer",
		"Emperor Karl Franz",
		"Balthasar Gelt",
		"Volkmar the Grim",
		"Markus Wulfhart",
		"Manfred von Carstein",
		"Helman Ghorst",
		"Vlad von Carstein",
		"Isabella von Carstein",
		"Heinrich Kemmler",
		"Grimgor Ironhide",
		"Azhag the Slaughter",
		"Wurrzag Da Great Green Prophet",
		"Skarsnik",
		"Khazrak the One-Eye",
		"Malagor the Dark Omen",
		"Morghur the Shadowgrave",
		"Archaon the Everchosen",
		"Sigvald the Magnificent",
		"Kholek Suneater",
		"King Louen Leoncoeur",
		"Alberic de Bordeleaux",
		"The Fay Enchantress",
		"Orion",
		"Durthu",
		"Wulfrik the Wanderer",
		"Throgg",
		"Tyrion",
		"Teclis",
		"Alith Anar",
		"Alarielle the Radiant",
		"Malekith",
		"Morathi",
		"Lokhir Fellheart",
		"Crone Hellebron",
		"Lord Mazdamundi",
		"Kroq-Gar",
		"Tiktaq'to",
		"Tehenauin",
		"Gor-Rok",
		"Nakai the Wanderer",
		"Queek Headtaker",
		"Lord Skrolk",
		"Tretch Craventail",
		"Ikit Claw",
		"Settra the Imperishable",
		"High Queen Khalida",
		"Grand Hierophant Khatep",
		"Arkhan the Black",
		"Luthor Harkon",
		"Count Noctilus",
		"Aranessa Saltspite",
		"Cylostra Direfin"
	};

	std::vector<std::string> Races = {
		"High Elves",
		"Dark Elves",
		"Lizardmen",
		"Skaven",
		"Tomb Kings",
		"Vampire Coast",
		"The Empire",
		"Dwarfs",
		"Vampire Counts",
		"Greenskins",
		"Beastmen",
		"Warriors of Chaos",
		"Bretonnia",
		"Wood Elves",
		"Norsca"
	};

	std::unordered_map<std::string, std::vector<std::string>> TotalFactions = {
		{"Dwarfs",
		{"Thorgrim Grudgebearer",
		"Ungrim Ironfist",
		"Grombrindal",
		"Belegar Ironhammer"}},
		{"The Empire", {"Emperor Karl Franz",
		"Balthasar Gelt",
		"Volkmar the Grim",
		"Markus Wulfhart"}},
		{"Vampire Counts", {"Manfred von Carstein",
		"Helman Ghorst",
		"Vlad von Carstein",
		"Isabella von Carstein",
		"Heinrich Kemmler"}},
		{"Greenskins", {"Grimgor Ironhide",
		"Azhag the Slaughter",
		"Wurrzag",
		"Skarsnik"}},
		{"Beastmen", {"Khazrak the One-Eye",
		"Malagor the Dark Omen",
		"Morghur the Shadowgrave"}},
		{"Warriors of Chaos", {"Archaon the Everchosen",
		"Sigvald the Magnificent",
		"Kholek Suneater"}},
		{"Bretonnia", {"King Louen Leoncoeur",
		"Alberic de Bordeleaux",
		"The Fay Enchantress"}},
		{"Wood Elves", {"Orion", "Durthu"}},
		{"Norsca", {"Wulfrik the Wanderer", "Throgg"}},
		{"High Elves", {"Tyrion",
		"Teclis",
		"Alith Anar",
		"Alarielle the Radiant"}},
		{"Dark Elves", {"Malekith",
		"Morathi",
		"Lokhir Fellheart",
		"Crone Hellebron"}},
		{"Lizardmen", {"Lord Mazdamundi",
		"Kroq-Gar",
		"Tiktaq'to",
		"Tehenauin",
		"Gor-Rok",
		"Nakai the Wanderer"}},
		{"Skaven", {"Queek Headtaker",
		"Lord Skrolk",
		"Tretch Craventail",
		"Ikit Claw"}},
		{"Tomb Kings", {"Settra the Imperishable",
		"High Queen Khalida",
		"Grand Hierophant Khatep",
		"Arkhan the Black"}},
		{"Vampire Coast", {"Luthor Harkon",
		"Count Noctilus",
		"Aranessa Saltspite",
		"Cylostra Direfin"}}
	};

	std::vector<std::string> WarhammerFilePaths = {
		"Warhammer faction pictures\\Beastmen\\Khazrak the One-Eye.png",
		"Warhammer faction pictures\\Beastmen\\Malagor the Dark Omen.png",
		"Warhammer faction pictures\\Beastmen\\Morghur the Shadowgrave.png",
		"Warhammer faction pictures\\Bretonnia\\Alberic de Bordeleaux.png",
		"Warhammer faction pictures\\Bretonnia\\King Louen Leoncoeur.png",
		"Warhammer faction pictures\\Bretonnia\\The Fay Enchantress.png",
		"Warhammer faction pictures\\Dark Elves\\Crone Hellebron.png",
		"Warhammer faction pictures\\Dark Elves\\Lokhir Fellheart.png",
		"Warhammer faction pictures\\Dark Elves\\Malekith.png",
		"Warhammer faction pictures\\Dark Elves\\Morathi.png",
		"Warhammer faction pictures\\Dwarfs\\Belegar Ironhammer.png",
		"Warhammer faction pictures\\Dwarfs\\Grombrindal.png",
		"Warhammer faction pictures\\Dwarfs\\Thorgrim Grudgebearer.png",
		"Warhammer faction pictures\\Dwarfs\\Ungrim Ironfist.png",
		"Warhammer faction pictures\\Greenskins\\Azhag the Slaughterer.png",
		"Warhammer faction pictures\\Greenskins\\Grimgor Ironhide.png",
		"Warhammer faction pictures\\Greenskins\\Skarsnik.png",
		"Warhammer faction pictures\\Greenskins\\Wurrzag Da Great Green Prophet.png",
		"Warhammer faction pictures\\High Elves\\Alarielle the Radiant.png",
		"Warhammer faction pictures\\High Elves\\Alith Anar.png",
		"Warhammer faction pictures\\High Elves\\Teclis.png",
		"Warhammer faction pictures\\High Elves\\Tyrion.png",
		"Warhammer faction pictures\\Lizardmen\\Gor-Rok.png",
		"Warhammer faction pictures\\Lizardmen\\Kroq-Gar.png",
		"Warhammer faction pictures\\Lizardmen\\Lord Mazdamundi.png",
		"Warhammer faction pictures\\Lizardmen\\Nakai the Wanderer.png",
		"Warhammer faction pictures\\Lizardmen\\Tehenauin.png",
		"Warhammer faction pictures\\Lizardmen\\Tiktaq'to.png",
		"Warhammer faction pictures\\Norsca\\Throgg.png",
		"Warhammer faction pictures\\Norsca\\Wulfrik the Wanderer.png",
		"Warhammer faction pictures\\Skaven\\Ikit Claw.png",
		"Warhammer faction pictures\\Skaven\\Lord Skrolk.png",
		"Warhammer faction pictures\\Skaven\\Queek Headtaker.png",
		"Warhammer faction pictures\\Skaven\\Tretch Craventail.png",
		"Warhammer faction pictures\\The Empire\\Balthasar Gelt.png",
		"Warhammer faction pictures\\The Empire\\Emperor Karl Franz.png",
		"Warhammer faction pictures\\The Empire\\Markus Wulfhart.png",
		"Warhammer faction pictures\\The Empire\\Volkmar the Grim.png",
		"Warhammer faction pictures\\Tomb Kings\\Arkhan the Black.png",
		"Warhammer faction pictures\\Tomb Kings\\Grand Hierophant Khatep.png",
		"Warhammer faction pictures\\Tomb Kings\\High Queen Khalida.png",
		"Warhammer faction pictures\\Tomb Kings\\Settra the Imperishable.png",
		"Warhammer faction pictures\\Vampire Coast\\Aranessa Saltspite.png",
		"Warhammer faction pictures\\Vampire Coast\\Count Noctilus.png",
		"Warhammer faction pictures\\Vampire Coast\\Cylostra Direfin.png",
		"Warhammer faction pictures\\Vampire Coast\\Luthor Harkon.png",
		"Warhammer faction pictures\\Vampire Counts\\Heinrich Kemmler.png",
		"Warhammer faction pictures\\Vampire Counts\\Helman Ghorst.png",
		"Warhammer faction pictures\\Vampire Counts\\Isabella von Carstein.png",
		"Warhammer faction pictures\\Vampire Counts\\Manfred von Carstein.png",
		"Warhammer faction pictures\\Vampire Counts\\Vlad von Carstein.png",
		"Warhammer faction pictures\\Warriors of Chaos\\Archaon the Everchosen.png",
		"Warhammer faction pictures\\Warriors of Chaos\\Kholek Suneater.png",
		"Warhammer faction pictures\\Warriors of Chaos\\Sigvald the Magnificent.png",
		"Warhammer faction pictures\\Wood Elves\\Durthu.png",
		"Warhammer faction pictures\\Wood Elves\\Orion.png"
	};

	std::vector<std::string> Vortex = {
		"Tyrion",
		"Teclis",
		"Alarielle the Radiant",
		"Alith Anar",
		"Malekith",
		"Morathi",
		"Crone Hellebron",
		"Lokhir Fellheart",
		"Lord Mazdamundi",
		"Kroq-Gar",
		"Tehenauin",
		"Tiktaq'to",
		"Nakai the Wanderer",
		"Gor-Rok",
		"Queek Headtaker",
		"Lord Skrolk",
		"Tretch Craventail",
		"Ikit Claw",
		"Luthor Harkon",
		"Count Noctilus",
		"Aranessa Saltspite",
		"Cylostra Direfin",
		"Settra the Imperishable",
		"Grand Hierophant Khatep",
		"High Queen Khalida",
		"Arkhan the Black",
		"Markus Wulfhart"
	};

	std::vector<std::string> VortexRaces = {
		"High Elves",
		"Dark Elves",
		"Lizardmen",
		"Skaven",
		"Vampire Coast",
		"Tomb Kings",
		"The Empire"
	};

	std::vector<std::string> ExcludeList = {};

	std::vector<std::string> ExcludeListRaces = {};
};